#!/usr/bin/env python3
"""Offline route-source regressions; all writes use a dedicated temporary HOME."""
from pathlib import Path
import json
import os
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
CLASH = ROOT / "clash-verge"
SOURCE = CLASH / "tun-fix.sh"
CORE = shutil.which("verge-mihomo")


def check(condition, message):
    if not condition:
        raise AssertionError(message)


def run(command, *, env, cwd, expected=0, input=None):
    result = subprocess.run(command, cwd=cwd, env=env, text=True, input=input,
                            capture_output=True, check=False)
    check(result.returncode == expected,
          f"unexpected rc {result.returncode}, expected {expected}:\n"
          f"$ {' '.join(command)}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}")
    return result


def write_rules(directory, direct, proxy):
    directory.mkdir()
    shutil.copy(CLASH / "rules" / "render-rules.py", directory / "render-rules.py")
    (directory / "direct.yaml").write_text(direct)
    (directory / "proxy.yaml").write_text(proxy)


def host_wrapped_js(script, config):
    """Model v2.5.2's JSON return path: throws would return original config."""
    program = r'''
const fs = require('fs'), vm = require('vm');
const sandbox = {}; vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(process.argv[1], 'utf8'), sandbox);
const original = JSON.parse(process.argv[2]);
let returned;
try {
  const serialized = JSON.stringify(sandbox.main(original) || '');
  const parsed = JSON.parse(serialized);
  if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') throw new Error('mapping required');
  returned = parsed;
} catch (_) {
  returned = original;
}
console.log(JSON.stringify(returned));
'''
    result = subprocess.run(["node", "-e", program, str(script), json.dumps(config)],
                            text=True, capture_output=True, check=True)
    return json.loads(result.stdout)


def core_validate(root, config, name, expected):
    config_file = root / f"{name}.yaml"
    subprocess.run(["python3", "-c", "import json,sys,yaml; yaml.safe_dump(json.load(sys.stdin), sys.stdout)",
                    ], input=json.dumps(config), text=True, stdout=config_file.open("w"), check=True)
    result = subprocess.run([CORE, "-t", "-f", str(config_file)], text=True,
                            capture_output=True, check=False)
    check(result.returncode == expected,
          f"core {name} rc={result.returncode}, expected {expected}:\n{result.stdout}\n{result.stderr}")
    return result.stdout + result.stderr


def main():
    for program in ("bash", "ssh", "node", "python3", "verge-mihomo"):
        check(shutil.which(program), f"missing prerequisite: {program}")
    run(["python3", "-c", "import yaml"], env=os.environ, cwd=ROOT)

    with tempfile.TemporaryDirectory(prefix="clash-rules-check-") as td:
        root = Path(td)
        home = root / "home"
        state = home / ".local/share/io.github.clash-verge-rev.clash-verge-rev"
        profiles = state / "profiles"
        profiles.mkdir(parents=True)
        rules = root / "rules"
        direct = '''version: 1
pre:
  - "DOMAIN,force.example,DIRECT"
  - "DOMAIN,ssh.github.com,DIRECT"
post:
  - "DOMAIN-SUFFIX,cn,DIRECT"
  - "IP-CIDR,2001:db8::/32,DIRECT,no-resolve"
  - "DOMAIN,deleted.example,DIRECT"
'''
        proxy = '''version: 1
pre:
  - "DOMAIN,proxy.example,Proxy"
post:
  - "DOMAIN,late.example,Proxy"
'''
        write_rules(rules, direct, proxy)
        # Quoted and reordered valid registry fields prove real-YAML lookup.
        (state / "profiles.yaml").write_text(
            "items:\n- file: 'Script.js'\n  type: script\n  uid: Script\n"
        )
        merge = profiles / "Merge.yaml"
        runtime = state / "clash-verge.yaml"
        ssh = home / ".ssh" / "config"
        merge.write_text("untouched merge\n")
        runtime.write_text("untouched runtime\n")
        ssh.parent.mkdir()
        ssh.write_text("Host untouched\n")
        env = dict(os.environ, HOME=str(home), RULES_DIR=str(rules))

        # Read-only paths use arbitrary cwd and no profile registry.
        no_profile = dict(env, HOME=str(root / "no-profile"))
        check("route sources valid: 7 rule(s)" in run(["bash", str(SOURCE), "rules", "check"], env=no_profile, cwd=root).stdout,
              "check did not read isolated sources")
        rendered = run(["bash", str(SOURCE), "rules", "render"], env=no_profile, cwd=root).stdout
        check(rendered.startswith("// Generated by tun-fix.sh"), "render missing ownership marker")
        check(not (root / "no-profile").exists(), "check/render wrote profile state")

        # Apply replaces only the registered Script and leaves unrelated state alone.
        run(["bash", str(SOURCE), "rules", "apply"], env=env, cwd=root)
        js = profiles / "Script.js"
        first = js.read_text()
        run(["bash", str(SOURCE), "rules", "apply"], env=env, cwd=root)
        check(js.read_text() == first, "repeat generated Script differs")
        check(merge.read_text() == "untouched merge\n" and runtime.read_text() == "untouched runtime\n" and ssh.read_text() == "Host untouched\n",
              "rules apply changed unrelated files")

        base = {"proxies": [], "proxy-groups": [{"name": "Proxy", "type": "select", "proxies": ["DIRECT"]}],
                "rules": ["DOMAIN-SUFFIX,example,DIRECT", "DOMAIN,force.example,DIRECT",
                          "DOMAIN,proxy.example,Proxy", "DOMAIN,subscription.cn,Proxy",
                          "DOMAIN-SUFFIX,cn,DIRECT", "MATCH,Proxy"]}
        ordered = host_wrapped_js(js, base)["rules"]
        check(ordered == [
            "DOMAIN,force.example,DIRECT", "DOMAIN,ssh.github.com,DIRECT", "DOMAIN,proxy.example,Proxy",
            "DOMAIN-SUFFIX,example,DIRECT", "DOMAIN,subscription.cn,Proxy", "DOMAIN-SUFFIX,cn,DIRECT",
            "IP-CIDR,2001:db8::/32,DIRECT,no-resolve", "DOMAIN,deleted.example,DIRECT",
            "DOMAIN,late.example,Proxy", "MATCH,Proxy"], f"unexpected ordering: {ordered}")
        check(core_validate(root, {**base, "rules": ordered}, "valid", 0), "valid core output unexpectedly empty")

        # Source-faithful host wrapper receives invalid JSON objects, not throws.
        missing_group = host_wrapped_js(js, {"proxies": [], "proxy-groups": [], "rules": ["MATCH,DIRECT"]})
        missing_group_output = core_validate(root, missing_group, "missing-group", 1)
        check("LOCAL-RULES-ERROR-MISSING-PROXY-GROUP" in missing_group_output,
              "missing group guard was not rejected by real core")
        missing_match = host_wrapped_js(js, {"proxies": [], "proxy-groups": [{"name": "Proxy", "type": "select", "proxies": ["DIRECT"]}], "rules": []})
        missing_match_output = core_validate(root, missing_match, "missing-match", 1)
        check("LOCAL-RULES-ERROR-MISSING-MATCH" in missing_match_output,
              "missing MATCH guard was not rejected by real core")

        # Strict grammar failures occur before candidate/backup/replacement.
        stable = js.read_text()
        for bad_rule, diagnostic in (
            ("DOMAIN-SUFIX,example.com,DIRECT", "unsupported matcher"),
            ("IP-CIDR,not-a-cidr,DIRECT,no-resolve", "valid IPv4 or IPv6 CIDR"),
            ("DST-PORT,70000,DIRECT", "DST-PORT payload"),
            ("DOMAIN,example.com,DIRECT,no-resolve", "no-resolve is not supported"),
            ("IP-CIDR,192.0.2.0/24,no-resolve,DIRECT", "only once as the final option"),
            ("IP-CIDR,192.0.2.0/24,DIRECT,no-resolve,no-resolve", "only once as the final option"),
        ):
            (rules / "direct.yaml").write_text(f'version: 1\npre:\n  - "{bad_rule}"\npost: []\n')
            checked_bad = run(["bash", str(SOURCE), "rules", "check"], env=env, cwd=root, expected=1)
            failed = run(["bash", str(SOURCE), "rules", "apply"], env=env, cwd=root, expected=1)
            check(diagnostic in checked_bad.stderr and diagnostic in failed.stderr and js.read_text() == stable,
                  f"invalid source {bad_rule} mutated Script or lacked diagnostic")

        # A bound legacy Rules extension blocks migration even after source removal.
        (rules / "direct.yaml").write_text(direct)
        (rules / "proxy.yaml").write_text('version: 1\npre:\n  - "DOMAIN,example.com,REJECT"\npost: []\n')
        reserved_target = run(["bash", str(SOURCE), "rules", "check"], env=env, cwd=root, expected=1)
        check("must name a subscription proxy group" in reserved_target.stderr, "proxy built-in target was accepted")
        (rules / "proxy.yaml").write_text(proxy)
        (state / "profiles.yaml").write_text(
            "items:\n- uid: Script\n  type: script\n  file: Script.js\n"
            "- uid: legacy-rules\n  type: rules\n  file: legacy.yaml\n"
            "- uid: remote-a\n  type: remote\n  option:\n    rules: legacy-rules\n"
        )
        legacy = profiles / "legacy.yaml"
        legacy.write_text('prepend:\n  - "DOMAIN,ssh.github.com,DIRECT"\nappend: []\n')
        refused = run(["bash", str(SOURCE), "rules", "apply"], env=env, cwd=root, expected=1)
        check(f"{legacy}:2: DOMAIN,ssh.github.com,DIRECT" in refused.stderr and js.read_text() == stable,
              "legacy GitHub duplicate was not reported before replacement")
        # Operator cleans only the named local extension; source removal then stops injection on a fresh base.
        legacy.write_text("prepend: []\nappend: []\n")
        (rules / "direct.yaml").write_text(direct.replace('  - "DOMAIN,ssh.github.com,DIRECT"\n', ""))
        run(["bash", str(SOURCE), "rules", "apply"], env=env, cwd=root)
        rebuilt = host_wrapped_js(js, {"proxies": [], "proxy-groups": [{"name": "Proxy", "type": "select", "proxies": ["DIRECT"]}],
                                       "rules": ["DOMAIN-SUFFIX,github.com,Proxy", "MATCH,Proxy"]})["rules"]
        check("DOMAIN,ssh.github.com,DIRECT" not in rebuilt and rebuilt[-1] == "MATCH,Proxy",
              "source removal still injected GitHub rule after migration cleanup")

        # Registry null/mixed duplicate Script entries reject without an orphan output.
        js.unlink()
        (state / "profiles.yaml").write_text("items:\n- uid: Script\n  type: script\n  file: null\n")
        run(["bash", str(SOURCE), "rules", "apply"], env=env, cwd=root, expected=1)
        check(not (profiles / "null").exists() and not js.exists(), "null registry file produced orphan")
        (state / "profiles.yaml").write_text("items: []\n")
        run(["bash", str(SOURCE), "rules", "apply"], env=env, cwd=root, expected=1)
        check(not js.exists(), "unregistered registry wrote output")
        (state / "profiles.yaml").write_text("items:\n- uid: Script\n  type: script\n  file: Script.js\n- uid: Script\n  type: merge\n  file: Other.yaml\n")
        run(["bash", str(SOURCE), "rules", "apply"], env=env, cwd=root, expected=1)
        check(not js.exists(), "duplicate mixed Script registry wrote output")

        # Confirmed foreign script has collision-free backups even for rapid applies.
        (state / "profiles.yaml").write_text("items:\n- uid: Script\n  type: script\n  file: Script.js\n")
        for prior_backup in profiles.glob("Script.js.backup.*"):
            prior_backup.unlink()
        js.write_text("// foreign script\n")
        run(["bash", str(SOURCE), "rules", "apply"], env=env, cwd=root, input="y\n")
        run(["bash", str(SOURCE), "rules", "apply"], env=env, cwd=root)
        backups = sorted(profiles.glob("Script.js.backup.*"))
        check(len(backups) >= 2 and any(backup.read_text() == "// foreign script\n" for backup in backups),
              "rapid applies overwrote the foreign-script backup")
        check(not list(profiles.glob(".Script.js.candidate.*")), "failed/finished apply left candidate files")

        # The pre-existing GitHub SSH generator remains callable from the new CLI source.
        ssh_block = run(["bash", "-c", 'source "$1"; github_ssh_block', "test", str(SOURCE)], env=env, cwd=root).stdout
        check("Host github.com ssh.github.com" in ssh_block and "IPQoS none" in ssh_block and
              "ProxyCommand" not in ssh_block and "ProxyJump" not in ssh_block,
              "GitHub SSH no-jump/QoS policy regressed")

    print("PASS: source grammar, YAML registry/migration preflight, host-faithful guard candidates, real Mihomo validation, atomic backups, ordering, and isolated scope")


if __name__ == "__main__":
    main()
