#!/usr/bin/env python3
"""End-to-end regressions for the retained routing manager.

Every fixture runs against a dedicated temporary HOME. Live Verge state, the
real ~/.ssh, the network, and the installed desktop apps are never touched:
`dpkg-query` and `ssh` are stubbed, and curl/openssl/ip/git invocations are
guarded so an accidental probe fails the test instead of reaching the network.

Runners in this directory:
  * tests/route-menu.py     menu/update/restore/SSH behavior and write boundaries
  * tests/app-integration.py rule grammar, registry, app expansion, Script guard
  * tests/discover-apps.py  native application discovery
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CLASH = ROOT / "clash-verge"
ENTRY = CLASH / "tun-fix.sh"
STATE_RELATIVE = ".local/share/io.github.clash-verge-rev.clash-verge-rev"
BACKUP_RE = re.compile(r"\.backup\.\d{8}_\d{6}(\.[A-Za-z0-9]+)?$")
FAKE_SSH_RESOLVED = """host github.com
hostname ssh.github.com
port 443
user git
identityfile ~/.ssh/conley
ipqos none none
connecttimeout 8
proxycommand none
proxyjump none
"""


def require(condition: object, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


class RouteMenuTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(prefix="clash-route-menu-")
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.home = self.root / "home"
        self.state = self.home / STATE_RELATIVE
        self.profiles = self.state / "profiles"
        self.rules = self.root / "rules"
        self.bin = self.root / "bin"
        self.install_root = self.root / "installed apps" / "wechat"
        for directory in (self.profiles, self.rules, self.bin, self.install_root):
            directory.mkdir(parents=True, exist_ok=True)
        (self.bin / "dpkg-query").write_text(
            "#!/bin/bash\n"
            "set -u\n"
            "log=\"${DPKG_LOG:?}\"\n"
            "printf '%s\\n' \"$*\" >> \"$log\"\n"
            "map=\"${DPKG_MAP:?}\"\n"
            "if [ \"${1:-}\" = '-W' ]; then\n"
            "  package=\"${3:-}\"\n"
            "  python3 -c 'import json,sys; sys.exit(0 if sys.argv[2] in json.load(open(sys.argv[1])) else 1)'"
            " \"$map\" \"$package\" && printf 'installed'\n"
            "  exit 0\n"
            "fi\n"
            "if [ \"${1:-}\" = '-L' ]; then\n"
            "  python3 -c 'import json,sys; print(\"\\n\".join(json.load(open(sys.argv[1])).get(sys.argv[2], [])))'"
            " \"$map\" \"${2:-}\"\n"
            "  exit 0\n"
            "fi\n"
            "exit 0\n",
            encoding="utf-8",
        )
        (self.bin / "dpkg-query").chmod(0o755)
        (self.bin / "ssh").write_text(
            "#!/bin/bash\n"
            "printf '%s\\n' \"$*\" >> \"${SSH_LOG:?}\"\n"
            "cat <<'EOF'\n" + FAKE_SSH_RESOLVED + "EOF\n",
            encoding="utf-8",
        )
        (self.bin / "ssh").chmod(0o755)
        self.probe_log = self.root / "guarded-probes.log"
        for probe in ("curl", "openssl", "ip", "git", "systemctl"):
            (self.bin / probe).write_text(
                "#!/bin/bash\n"
                f"printf '%s %s\\n' '{probe}' \"$*\" >> {self.probe_log}\n"
                f"printf 'unexpected probe: {probe}\\n' >&2\n"
                "exit 90\n",
                encoding="utf-8",
            )
            (self.bin / probe).chmod(0o755)

        self.ssh_config = self.home / ".ssh" / "config"
        self.ssh_config.parent.mkdir(parents=True)
        self.ssh_config.write_text("# existing host\nHost existing.example\n    Port 22\n", encoding="utf-8")

        self.app_executable = self.install_root / "wechat"
        self.app_executable.write_bytes(b"\x7fELFfixture")
        self.app_executable.chmod(0o755)
        self.manifest = self.root / "manifest.json"
        self.manifest.write_text(json.dumps({}), encoding="utf-8")
        self.dpkg_log = self.root / "dpkg.log"
        self.ssh_log = self.root / "ssh.log"

        self.script = self.profiles / "Script.js"
        self.script.write_text("// Generated by tun-fix.sh earlier revision\n", encoding="utf-8")
        (self.profiles / "Merge.yaml").write_text("# merge sentinel\nmode: rule\n", encoding="utf-8")
        (self.profiles / "subscription-merge.yaml").write_text("# subscription merge sentinel\n", encoding="utf-8")
        (self.profiles / "SubscriptionRules.yaml").write_text("prepend: []\nappend: []\n", encoding="utf-8")
        (self.profiles / "subscription.yaml").write_text("proxies: []\nrules:\n  - MATCH,DIRECT\n", encoding="utf-8")
        (self.state / "clash-verge.yaml").write_text("# runtime sentinel\n", encoding="utf-8")
        (self.state / "verge.yaml").write_text("# app settings sentinel\n", encoding="utf-8")
        self.write_registry()
        self.write_rules()

    # ---- fixtures -------------------------------------------------------
    def write_registry(self, script: str | None = None, with_merge_binding: bool = True) -> None:
        script_item = script or (
            "- uid: Script\n  type: script\n  file: Script.js\n  name: Global Script\n"
        )
        remote_option = ("    merge: remote-merge\n    rules: SubscriptionRules\n"
                         if with_merge_binding else "    rules: SubscriptionRules\n")
        registry = (
            "current: remote-a\nitems:\n"
            + script_item
            + "- uid: SubscriptionRules\n  type: rules\n  file: SubscriptionRules.yaml\n"
            + "- uid: remote-merge\n  type: merge\n  file: subscription-merge.yaml\n"
            + "- uid: Merge\n  type: merge\n  file: Merge.yaml\n"
            + "- uid: remote-a\n  type: remote\n  name: Fixed Profile\n  file: subscription.yaml\n"
            + "  option:\n" + remote_option
        )
        (self.state / "profiles.yaml").write_text(registry, encoding="utf-8")

    def write_rules(self, direct: str | None = None, proxy: str | None = None) -> None:
        (self.rules / "direct.yaml").write_text(direct or (
            'version: 1\npre:\n  - "DOMAIN,force.example,DIRECT"\n'
            'post:\n  - "DOMAIN-SUFFIX,cn,DIRECT"\n'
        ), encoding="utf-8")
        (self.rules / "proxy.yaml").write_text(proxy or (
            'version: 1\npre: []\npost: []\n'
        ), encoding="utf-8")

    def declare_wechat_proxy(self, installed: bool = True) -> None:
        self.write_rules(proxy=(
            'version: 1\npre:\n  - app: wechat\n    target: Proxy\npost: []\n'
        ))
        packages = {"wechat": [str(self.app_executable)]} if installed else {}
        self.manifest.write_text(json.dumps(packages), encoding="utf-8")

    # ---- drivers --------------------------------------------------------
    def environment(self, **overrides: object) -> dict[str, str]:
        environment = dict(os.environ)
        environment.update({
            "HOME": str(self.home),
            "RULES_DIR": str(self.rules),
            "PATH": f"{self.bin}:{os.environ['PATH']}",
            "DPKG_LOG": str(self.dpkg_log),
            "DPKG_MAP": str(self.manifest),
            "SSH_LOG": str(self.ssh_log),
            "PROBE_LOG": str(self.probe_log),
        })
        environment.update({key: str(value) for key, value in overrides.items()})
        return environment

    def run_menu(self, *inputs: str, expected: int = 0, cwd: Path | None = None,
                 environment: dict[str, str] | None = None, script: Path | None = None) -> subprocess.CompletedProcess:
        result = subprocess.run(
            ["bash", str(script or ENTRY)], cwd=str(cwd or self.root),
            env=environment or self.environment(), input="".join(inputs),
            text=True, capture_output=True, check=False, timeout=120,
        )
        self.assertEqual(
            result.returncode, expected,
            f"menu rc={result.returncode}, expected {expected}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}",
        )
        if self.probe_log.exists():
            self.fail("a guarded network command ran: " + self.probe_log.read_text())
        return result

    def run_entry(self, *arguments: str, expected: int = 0, input: str | None = None,
                  cwd: Path | None = None, environment: dict[str, str] | None = None) -> subprocess.CompletedProcess:
        result = subprocess.run(
            ["bash", str(ENTRY), *arguments], cwd=str(cwd or self.root),
            env=environment or self.environment(), input=input,
            text=True, capture_output=True, check=False, timeout=120,
        )
        self.assertEqual(
            result.returncode, expected,
            f"entry rc={result.returncode}, expected {expected}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}",
        )
        return result

    # ---- helpers --------------------------------------------------------
    def snapshot(self, include_mtime: bool = False) -> dict[str, object]:
        """Byte snapshot of every fixture file outside the temporary tool dirs."""
        watched = [self.state, self.home / ".ssh", self.rules]
        snapshot: dict[str, object] = {}
        for base in watched:
            for path in sorted(base.rglob("*")):
                if path.is_symlink():
                    snapshot[str(path)] = ("symlink", os.readlink(path))
                    continue
                if not path.is_file():
                    snapshot[str(path)] = ("directory", stat.S_IMODE(path.stat().st_mode))
                    continue
                entry: dict[str, object] = {"sha256": digest(path), "mode": stat.S_IMODE(path.stat().st_mode)}
                if include_mtime:
                    entry["mtime_ns"] = path.stat().st_mtime_ns
                snapshot[str(path)] = entry
        return snapshot

    def backups(self) -> list[Path]:
        return sorted(path for path in self.profiles.glob(f"{self.script.name}.backup.*") if path.is_file())

    def changed_paths(self, before: dict[str, object], after: dict[str, object]) -> set[str]:
        return {path for path in set(before) | set(after) if before.get(path) != after.get(path)}

    # ---- menu presentation ---------------------------------------------
    def test_bare_menu_prints_absolute_paths_and_blank_line_updates(self) -> None:
        self.declare_wechat_proxy()
        result = self.run_menu("\n", "0\n", cwd=self.root)
        output = result.stdout
        self.assertIn(str(self.rules / "direct.yaml"), output)
        self.assertIn(str(self.rules / "proxy.yaml"), output)
        self.assertIn(str(self.script), output)
        self.assertIn("更新直连/代理规则（默认，回车执行）", output)
        self.assertIn("配置 GitHub SSH", output)
        self.assertIn("查看本机应用识别结果", output)
        self.assertIn("恢复上次规则", output)
        self.assertTrue(self.script.read_text().startswith("// Generated by tun-fix.sh from rules/direct.yaml"))
        self.assertIn(str(self.app_executable), self.script.read_text())
        self.assertEqual(len(self.backups()), 1)
        self.assertIn("重载", output)

    def test_menu_paths_use_invocation_relative_overrides(self) -> None:
        relative_env = dict(self.environment())
        relative_env["RULES_DIR"] = os.path.relpath(self.rules, self.root)
        relative_env["CLASH_DIR"] = os.path.relpath(self.state, self.root)
        result = self.run_menu("0\n", environment=relative_env, cwd=self.root)
        self.assertIn(str(self.rules / "direct.yaml"), result.stdout)
        self.assertIn(str(self.script), result.stdout)

    def test_missing_relative_overrides_still_print_absolute_paths(self) -> None:
        """A relative override that does not exist must not print a relative path."""
        workdir = self.root / "arbitrary cwd"
        workdir.mkdir()
        environment = self.environment()
        environment["RULES_DIR"] = "./missing rules"
        environment["CLASH_DIR"] = "missing-state"
        result = self.run_menu("3\n", "0\n", cwd=workdir, environment=environment)
        self.assertIn(str(workdir / "missing rules" / "direct.yaml"), result.stdout)
        self.assertIn(str(workdir / "missing rules" / "proxy.yaml"), result.stdout)
        self.assertIn(str(workdir / "missing-state" / "profiles.yaml"), result.stdout)
        self.assertIn("不可用", result.stdout)
        self.assertIn("已支持的应用 ID", result.stdout)
        self.assertFalse((workdir / "missing rules").exists())
        self.assertFalse((workdir / "missing-state").exists())

    def test_invalid_choice_returns_to_menu_and_failed_action_sets_exit_status(self) -> None:
        invalid = self.run_menu("bogus\n", "0\n")
        self.assertIn("无效选择", invalid.stdout)

        self.write_rules(proxy=('version: 1\npre:\n  - app: wechat\n    target: Proxy\npost: []\n'))
        self.manifest.write_text(json.dumps({}), encoding="utf-8")
        failed = self.run_menu("\n", "0\n", expected=1)
        self.assertIn("更新失败", failed.stdout)
        self.assertIn("no known installed package manifest entry", failed.stderr)
        self.assertEqual(self.backups(), [])
        self.assertFalse(list(self.profiles.glob(".Script.js.candidate.*")))

    def test_eof_exits_without_any_write_or_backup(self) -> None:
        before = self.snapshot(include_mtime=True)
        result = self.run_menu()
        self.assertIn("输入结束", result.stdout)
        self.assertEqual(self.changed_paths(before, self.snapshot(include_mtime=True)), set())
        self.assertEqual(self.backups(), [])

    def test_registry_without_merge_or_current_still_offers_discovery_and_ssh(self) -> None:
        self.write_registry(script="- uid: Script\n  type: script\n  file: Script.js\n")
        discovery = self.run_menu("3\n", "0\n")
        self.assertIn("已支持的应用 ID", discovery.stdout)
        ssh = self.run_menu("2\n", "n\n", "0\n")
        self.assertIn("配置 GitHub SSH", ssh.stdout)

        (self.state / "profiles.yaml").unlink()
        no_registry = self.run_menu("0\n")
        self.assertIn("不可用", no_registry.stdout)
        self.assertIn("未找到", no_registry.stdout)
        discovery_without_registry = self.run_menu("3\n", "0\n")
        self.assertIn("已支持的应用 ID", discovery_without_registry.stdout)
        ssh_without_registry = self.run_menu("2\n", "n\n", "0\n")
        self.assertIn("配置 GitHub SSH", ssh_without_registry.stdout)

    def test_malformed_script_binding_is_reported_without_orphan_write(self) -> None:
        (self.state / "profiles.yaml").write_text(
            "items:\n- uid: Script\n  type: script\n  file: null\n", encoding="utf-8")
        result = self.run_menu("\n", "0\n", expected=1)
        self.assertIn("不可用", result.stdout)
        self.assertFalse((self.profiles / "null").exists())
        self.assertEqual(self.backups(), [])

    # ---- update ownership ----------------------------------------------
    def test_update_touches_only_registered_script_and_its_backups(self) -> None:
        self.declare_wechat_proxy()
        before = self.snapshot(include_mtime=True)
        self.run_menu("1\n", "0\n")
        after = self.snapshot(include_mtime=True)
        changed = self.changed_paths(before, after)
        allowed = {str(self.script)} | {str(path) for path in self.backups()}
        self.assertTrue(changed <= allowed, f"update touched unexpected paths: {sorted(changed - allowed)}")
        self.assertIn(str(self.script), changed)
        self.assertEqual(len(self.backups()), 1)
        require(BACKUP_RE.search(self.backups()[0].name), self.backups()[0].name)
        self.assertEqual((self.profiles / "Merge.yaml").read_text(), "# merge sentinel\nmode: rule\n")
        self.assertEqual((self.profiles / "subscription-merge.yaml").read_text(), "# subscription merge sentinel\n")
        self.assertEqual((self.state / "clash-verge.yaml").read_text(), "# runtime sentinel\n")
        self.assertEqual(self.ssh_config.read_text(), "# existing host\nHost existing.example\n    Port 22\n")
        self.assertFalse(self.ssh_log.exists(), "routing update invoked ssh")
        for sentinel in ("Merge.yaml", "subscription-merge.yaml", "SubscriptionRules.yaml", "subscription.yaml"):
            self.assertEqual(digest(self.profiles / sentinel),
                             before[str(self.profiles / sentinel)]["sha256"], sentinel)

    def test_registry_merge_registration_is_not_required_for_routing(self) -> None:
        self.declare_wechat_proxy()
        (self.state / "profiles.yaml").write_text(
            "current: remote-a\nitems:\n"
            "- uid: Script\n  type: script\n  file: Script.js\n"
            "- uid: remote-a\n  type: remote\n  name: Fixed Profile\n  file: subscription.yaml\n",
            encoding="utf-8",
        )
        self.run_menu("\n", "0\n")
        self.assertIn("PROCESS-PATH", self.script.read_text())
        self.assertEqual(list(self.profiles.glob("Merge.yaml*")), [self.profiles / "Merge.yaml"])

    def test_identical_output_is_noop_including_mtime_permissions_and_backups(self) -> None:
        self.declare_wechat_proxy()
        self.run_menu("\n", "0\n")
        self.script.chmod(0o640)
        before = self.snapshot(include_mtime=True)
        backup_names = [path.name for path in self.backups()]
        second = self.run_menu("1\n", "0\n")
        self.assertIn("无需更新", second.stdout)
        self.assertEqual(self.changed_paths(before, self.snapshot(include_mtime=True)), set())
        self.assertEqual([path.name for path in self.backups()], backup_names)
        self.assertEqual(stat.S_IMODE(self.script.stat().st_mode), 0o640)

    def test_source_files_stay_byte_identical_and_are_never_written_back(self) -> None:
        self.declare_wechat_proxy()
        direct_before = digest(self.rules / "direct.yaml")
        proxy_before = digest(self.rules / "proxy.yaml")
        self.run_menu("\n", "\n", "0\n")
        self.assertEqual(digest(self.rules / "direct.yaml"), direct_before)
        self.assertEqual(digest(self.rules / "proxy.yaml"), proxy_before)

    def test_declared_app_expands_from_one_discovery_in_authored_position(self) -> None:
        self.write_rules(
            direct='version: 1\npre:\n  - "DOMAIN,before.example,DIRECT"\n  - app: wechat\npost:\n  - "DOMAIN,after.example,DIRECT"\n',
            proxy='version: 1\npre: []\npost: []\n',
        )
        self.manifest.write_text(json.dumps({"wechat": [str(self.app_executable)]}), encoding="utf-8")
        self.run_menu("\n", "0\n")
        rendered = self.script.read_text()
        expected_prefix = (
            '  "pre": [\n'
            '    "DOMAIN,before.example,DIRECT",\n'
            f'    "PROCESS-PATH,{self.app_executable},DIRECT"\n'
            '  ],\n'
        )
        self.assertIn(expected_prefix, rendered)
        discovery_calls = [line for line in self.dpkg_log.read_text().splitlines() if line.startswith("-L")]
        self.assertEqual(len(discovery_calls), 1, discovery_calls)

    def test_missing_declared_app_fails_before_backup_or_write(self) -> None:
        self.write_rules(proxy='version: 1\npre:\n  - app: wechat\n    target: Proxy\npost: []\n')
        self.manifest.write_text(json.dumps({}), encoding="utf-8")
        stable = digest(self.script)
        result = self.run_menu("\n", "0\n", expected=1)
        self.assertIn("cannot resolve PROCESS-PATH", result.stderr)
        self.assertEqual(digest(self.script), stable)
        self.assertEqual(self.backups(), [])
        self.assertFalse(list(self.profiles.glob(".Script.js.candidate.*")))

    def test_conflicting_app_selectors_fail_before_write(self) -> None:
        self.write_rules(
            direct='version: 1\npre:\n  - app: wechat\npost: []\n',
            proxy='version: 1\npre:\n  - app: wechat\n    target: Proxy\npost: []\n',
        )
        self.manifest.write_text(json.dumps({"wechat": [str(self.app_executable)]}), encoding="utf-8")
        stable = digest(self.script)
        result = self.run_menu("\n", "0\n", expected=1)
        self.assertIn("selector conflicts", result.stderr)
        self.assertEqual(digest(self.script), stable)
        self.assertEqual(self.backups(), [])

    def test_legacy_bound_extension_blocks_migration_until_cleaned(self) -> None:
        self.declare_wechat_proxy()
        (self.profiles / "SubscriptionRules.yaml").write_text(
            'prepend:\n  - "DOMAIN,force.example,DIRECT"\nappend: []\n', encoding="utf-8")
        stable = digest(self.script)
        refused = self.run_menu("\n", "0\n", expected=1)
        self.assertIn("DOMAIN,force.example,DIRECT", refused.stderr)
        self.assertEqual(digest(self.script), stable)
        (self.profiles / "SubscriptionRules.yaml").write_text("prepend: []\nappend: []\n", encoding="utf-8")
        self.run_menu("\n", "0\n")
        self.assertNotIn("ssh.github.com", self.script.read_text())

    def test_foreign_script_requires_confirmation_and_never_treats_eof_as_yes(self) -> None:
        self.script.write_text("// my own routing script\n")
        stable = digest(self.script)
        eof = self.run_menu("\n")
        self.assertIn("覆盖它？", eof.stdout)
        self.assertIn("未写入任何配置", eof.stdout)
        self.assertEqual(digest(self.script), stable)
        self.assertEqual(self.backups(), [])
        self.assertFalse(list(self.profiles.glob(".Script.js.candidate.*")))

        declined = self.run_menu("\n", "n\n", "0\n")
        self.assertIn("已取消", declined.stdout)
        self.assertEqual(digest(self.script), stable)
        self.assertEqual(self.backups(), [])

        confirmed = self.run_menu("\n", "y\n", "0\n")
        self.assertEqual(len(self.backups()), 1)
        self.assertEqual(self.backups()[0].read_text(), "// my own routing script\n")
        self.assertTrue(self.script.read_text().startswith("// Generated by tun-fix.sh"))

    def test_rapid_applies_keep_collision_free_backups(self) -> None:
        self.declare_wechat_proxy()
        self.run_menu("\n", "0\n")
        first_backup = self.backups()[0]
        self.write_rules(direct=(
            'version: 1\npre:\n  - "DOMAIN,second.example,DIRECT"\npost: []\n'
        ))
        self.run_menu("1\n", "0\n")
        names = [path.name for path in self.backups()]
        self.assertEqual(len(names), 2, names)
        self.assertEqual(len(set(names)), 2)
        self.assertTrue(all(BACKUP_RE.search(name) for name in names), names)
        self.assertEqual(first_backup.read_text().startswith("// Generated by tun-fix.sh"), True)
        self.assertIn("second.example", self.script.read_text())

    def test_success_message_scopes_the_write_and_asks_for_manual_reload(self) -> None:
        self.declare_wechat_proxy()
        result = self.run_menu("\n", "0\n")
        self.assertIn("只写了全局 Script", result.stdout)
        self.assertIn("Verge 中重载", result.stdout)
        self.assertNotIn("已生效", result.stdout)

    def test_apply_entrypoint_reports_cancel_with_exit_code_two(self) -> None:
        self.script.write_text("// foreign\n")
        refused = self.run_entry("rules", "apply", expected=2, input="n\n")
        self.assertIn("已取消", refused.stdout)
        self.assertEqual(self.script.read_text(), "// foreign\n")
        self.assertEqual(self.backups(), [])
        self.run_entry("rules", "apply", input="y\n")
        self.assertTrue(self.script.read_text().startswith("// Generated by tun-fix.sh"))
        self.assertEqual(len(self.backups()), 1)

    # ---- restore-last ---------------------------------------------------
    def make_backup(self, name: str, content: str, mtime: int, mtime_ns: int | None = None) -> Path:
        path = self.profiles / f"{self.script.name}.backup.{name}"
        path.write_text(content, encoding="utf-8")
        if mtime_ns is None:
            os.utime(path, (mtime, mtime))
        else:
            os.utime(path, ns=(mtime_ns, mtime_ns))
        return path

    def test_restore_selects_newest_valid_regular_backup_only(self) -> None:
        # Timestamp-only, numeric and random suffixes are all tool-written shapes.
        older = self.make_backup("20250101_010101", "older backup\n", 1_600_000_000)
        older_numeric = self.make_backup("20250101_010101.2", "older numeric\n", 1_610_000_000)
        newer = self.make_backup("20250101_010102.AbC123", "newer backup\n", 1_700_000_000)
        unrelated = self.profiles / "Merge.yaml.backup.20250101_010103.zzz"
        unrelated.write_text("unrelated merge backup\n", encoding="utf-8")
        os.utime(unrelated, (1_900_000_000, 1_900_000_000))
        symlink = self.profiles / f"{self.script.name}.backup.20250101_010104"
        symlink.symlink_to(older)
        invalid = self.profiles / f"{self.script.name}.backup.not-a-timestamp"
        invalid.write_text("invalid name\n", encoding="utf-8")
        os.utime(invalid, (1_950_000_000, 1_950_000_000))
        directory = self.profiles / f"{self.script.name}.backup.20250101_010105"
        directory.mkdir()
        os.utime(directory, (1_960_000_000, 1_960_000_000))

        self.script.write_text("// current generated\n", encoding="utf-8")
        result = self.run_menu("4\n", "y\n", "0\n")
        self.assertIn(str(newer), result.stdout)
        self.assertEqual(self.script.read_text(), "newer backup\n")
        self.assertTrue(older.exists() and older_numeric.exists() and unrelated.exists() and invalid.exists()
                        and directory.is_dir())
        self.assertEqual(self.ssh_config.read_text(), "# existing host\nHost existing.example\n    Port 22\n")
        backups = self.backups()
        current_copy = [path for path in backups if path.read_text() == "// current generated\n"]
        self.assertEqual(len(current_copy), 1, [path.name for path in backups])
        self.assertNotEqual(current_copy[0], newer)
        self.assertIn("重载", result.stdout)
        self.assertIn("direct.yaml 与 rules/proxy.yaml 未改动", result.stdout)

    def test_restore_ignores_exact_ties_and_deterministically_picks_last_name(self) -> None:
        stamp = 1_700_000_000_000_000_000
        first = self.make_backup("20250101_010101", "tie one\n", 1_700_000_000, stamp)
        second = self.make_backup("20250101_010102", "tie two\n", 1_700_000_000, stamp)
        self.run_menu("4\n", "y\n", "0\n")
        self.assertEqual(self.script.read_text(), "tie two\n")
        self.assertTrue(first.exists() and second.exists())

    def test_restore_orders_same_second_backups_by_nanoseconds_not_by_name(self) -> None:
        """`.2` vs `.10` inside one clock second: the name lies, mtime_ns does not."""
        base = 1_700_000_002_000_000_000
        older = self.make_backup("20250101_010102.2", "older\n", 1_700_000_002, base + 2)
        newer = self.make_backup("20250101_010102.10", "newer\n", 1_700_000_002, base + 10)
        self.run_menu("4\n", "y\n", "0\n")
        self.assertEqual(self.script.read_text(), "newer\n", "lexicographic suffix order won")
        self.assertTrue(older.exists() and newer.exists())

    def test_restore_stage_is_exclusive_and_never_follows_a_planted_path(self) -> None:
        """A `.<Script>.restore.$$` path planted before the run must stay untouched."""
        backup = self.make_backup("20250101_010101", "restorable\n", 1_700_000_000)
        self.script.write_text("// current generated\n", encoding="utf-8")
        sentinel = self.profiles / "planted-target.js"
        sentinel.write_text("// sentinel\n", encoding="utf-8")
        record = self.root / "planted-path.txt"
        wrapper = (
            'planted="$STAGE_DIR/.Script.js.restore.$$"; '
            'ln -s "$SENTINEL" "$planted"; printf "%s" "$planted" > "$PLANTED_RECORD"; '
            'exec bash "$0"'
        )
        environment = self.environment()
        environment["SENTINEL"] = str(sentinel)
        environment["STAGE_DIR"] = str(self.profiles)
        environment["PLANTED_RECORD"] = str(record)
        result = subprocess.run(
            ["bash", "-c", wrapper, str(ENTRY)], cwd=str(self.root), env=environment,
            input="4\ny\n0\n", text=True, capture_output=True, check=False, timeout=120,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        planted = Path(record.read_text())
        # The wrapper's own `$$` survives the exec, so this is exactly the
        # predictable stage path the pre-mktemp implementation used.
        self.assertTrue(planted.is_symlink(), "wrapper did not plant the predictable stage name")
        self.assertRegex(planted.name, r"^\.Script\.js\.restore\.\d+$")
        self.assertEqual(sentinel.read_text(), "// sentinel\n", "restore wrote through a planted path")
        self.assertEqual(self.script.read_text(), "restorable\n")
        self.assertFalse(self.script.is_symlink(), "restore moved the planted symlink over the target")
        self.assertEqual(sorted(path.name for path in self.profiles.glob(".Script.js.restore.*")),
                         [planted.name], "an unexpected stage name was used or left behind")
        self.assertEqual(backup.read_text(), "restorable\n")

    def test_backup_names_keep_the_timestamp_prefix_with_an_exclusive_suffix(self) -> None:
        (self.profiles / "Sample.js").write_text("sample\n", encoding="utf-8")
        environment = self.environment()
        first = subprocess.run(
            ["bash", "-c", 'source "$1"; unique_backup "$2"', "test", str(ENTRY),
             str(self.profiles / "Sample.js")],
            cwd=str(self.root), env=environment, text=True, capture_output=True, check=False, timeout=60,
        )
        second = subprocess.run(
            ["bash", "-c", 'source "$1"; unique_backup "$2"', "test", str(ENTRY),
             str(self.profiles / "Sample.js")],
            cwd=str(self.root), env=environment, text=True, capture_output=True, check=False, timeout=60,
        )
        names = [Path(first.stdout.strip()).name, Path(second.stdout.strip()).name]
        self.assertEqual(len(set(names)), 2, names)
        for name in names:
            self.assertRegex(name, r"^Sample\.js\.backup\.\d{8}_\d{6}\.[A-Za-z0-9]+$")
        for name in names:
            self.assertEqual((self.profiles / name).read_text(), "sample\n")
        # Older layouts stay selectable: timestamp-only, numeric and random suffixes.
        for name in ("20250101_010101", "20250101_010101.2", "20250101_010101.AbC123"):
            self.assertRegex(name, r"^\d{8}_\d{6}(\.[A-Za-z0-9]+)?$")

    def test_restore_declined_eof_and_missing_backup_write_nothing(self) -> None:
        backup = self.make_backup("20250101_010101", "restorable\n", 1_700_000_000)
        self.script.write_text("// current generated\n")
        before = self.snapshot(include_mtime=True)

        declined = self.run_menu("4\n", "n\n", "0\n")
        self.assertIn("已取消", declined.stdout)
        self.assertEqual(self.changed_paths(before, self.snapshot(include_mtime=True)), set())

        eof = self.run_menu("4\n")
        self.assertIn("输入结束", eof.stdout)
        self.assertEqual(self.changed_paths(before, self.snapshot(include_mtime=True)), set())

        backup.unlink()
        missing = self.run_menu("4\n", "y\n", "0\n")
        self.assertIn("没有找到", missing.stdout)
        self.assertEqual(self.script.read_text(), "// current generated\n")
        self.assertEqual(self.backups(), [])

    def test_restore_without_current_target_does_not_delete_or_invent_state(self) -> None:
        backup = self.make_backup("20250101_010101", "restorable\n", 1_700_000_000)
        self.script.unlink()
        result = self.run_menu("4\n", "y\n", "0\n")
        self.assertIn(str(backup), result.stdout)
        self.assertEqual(self.script.read_text(), "restorable\n")
        self.assertEqual(len(self.backups()), 1)

    def test_restore_replaces_symlinked_target_content_atomically(self) -> None:
        self.make_backup("20250101_010101", "restorable\n", 1_700_000_000)
        outside = self.root / "outside-script.js"
        outside.write_text("// outside\n", encoding="utf-8")
        self.script.unlink()
        self.script.symlink_to(outside)
        self.run_menu("4\n", "y\n", "0\n")
        self.assertFalse(self.script.is_symlink(), "atomic replace must not write through the link")
        self.assertEqual(self.script.read_text(), "restorable\n")
        self.assertEqual(outside.read_text(), "// outside\n")

    def test_restore_only_accepts_the_registered_basename(self) -> None:
        other = self.profiles / "Other.js.backup.20250101_010101"
        other.write_text("other script backup\n", encoding="utf-8")
        os.utime(other, (1_900_000_000, 1_900_000_000))
        before = self.snapshot(include_mtime=True)
        result = self.run_menu("4\n", "y\n", "0\n")
        self.assertIn("没有找到", result.stdout)
        self.assertEqual(self.changed_paths(before, self.snapshot(include_mtime=True)), set())

    # ---- SSH write path -------------------------------------------------
    def unowned_ssh_config(self, hosts: int = 40) -> str:
        original = "# existing host\n" + "".join(
            f"Host host{i}.example\n    Port 22{i:02d}\n" for i in range(hosts)
        )
        self.ssh_config.write_text(original, encoding="utf-8")
        self.ssh_config.chmod(0o644)
        return original

    def ssh_failure_environment(self) -> dict[str, str]:
        environment = self.environment()
        environment["PYTHONDONTWRITEBYTECODE"] = "1"
        return environment

    def assert_ssh_write_failed_closed(self, before_bytes: bytes, *, backups: int) -> None:
        self.assertEqual(self.ssh_config.read_bytes(), before_bytes, "original SSH config changed")
        self.assertEqual(stat.S_IMODE(self.ssh_config.stat().st_mode), 0o644, "original mode changed")
        leftovers = sorted(
            path.name for path in self.ssh_config.parent.iterdir()
            if ".config." in path.name and path.name != self.ssh_config.name
        )
        self.assertEqual(leftovers, [], f"candidate temporaries leaked: {leftovers}")
        self.assertEqual(len(list(self.ssh_config.parent.glob(f"{self.ssh_config.name}.backup.*"))), backups)
        # The static ssh -G check must not run (and must not be claimed) for a
        # failed write: the stub only logs when it is actually invoked.
        self.assertFalse(self.ssh_log.exists(), "ssh -G ran despite a failed write")

    def test_ssh_render_and_commit_failures_never_replace_the_real_config(self) -> None:
        """cat/commit failures and a directory target must fail before any change."""
        environment = self.ssh_failure_environment()

        # (a) the copy of the original fails: nothing staged, nothing backed up.
        original = self.unowned_ssh_config()
        before = self.ssh_config.read_bytes()
        failing_cat = self.bin / "cat"
        failing_cat.write_text(
            "#!/bin/bash\n"
            "for a in \"$@\"; do\n"
            "  if [ \"$a\" = \"${SSH_FAIL_CAT:-}\" ]; then printf 'cat: injected failure\\n' >&2; exit 5; fi\n"
            "done\n"
            "exec /bin/cat \"$@\"\n",
            encoding="utf-8",
        )
        failing_cat.chmod(0o755)
        failed = self.run_menu("2\n", "0\n", expected=1,
                               environment=dict(environment, SSH_FAIL_CAT=str(self.ssh_config)))
        self.assertIn("fail 读取", failed.stdout + failed.stderr)
        self.assertNotIn("pass SSH 配置已原子写入", failed.stdout)
        self.assertNotIn("pass SSH 解析为", failed.stdout)
        self.assert_ssh_write_failed_closed(before, backups=0)

        # (b) the commit rename fails: the truthful pre-change backup exists, the
        # original still holds every unrelated Host block.
        failing_cat.unlink()
        failing_mv = self.bin / "mv"
        failing_mv.write_text("#!/bin/bash\nprintf 'mv: injected failure\\n' >&2\nexit 6\n", encoding="utf-8")
        failing_mv.chmod(0o755)
        failed = self.run_menu("2\n", "0\n", expected=1)
        self.assertIn("fail 写入", failed.stdout + failed.stderr)
        self.assertNotIn("pass SSH 配置已原子写入", failed.stdout)
        self.assert_ssh_write_failed_closed(before, backups=1)
        backup = next(self.ssh_config.parent.glob(f"{self.ssh_config.name}.backup.*"))
        self.assertEqual(backup.read_bytes(), before, "backup is not a truthful pre-change copy")
        self.assertIn("Host host39.example", self.ssh_config.read_text())
        failing_mv.unlink()

        # (c) a directory at the target path fails before chmod/staging.
        backups_before = sorted(path.name for path in self.ssh_config.parent.glob(f"{self.ssh_config.name}.backup.*"))
        self.ssh_config.unlink()
        self.ssh_config.mkdir()
        self.ssh_config.chmod(0o755)
        ssh_dir_mode = stat.S_IMODE(self.ssh_config.parent.stat().st_mode)
        failed = self.run_menu("2\n", "0\n", expected=1)
        self.assertIn("不是普通文件", failed.stdout + failed.stderr)
        self.assertNotIn("pass SSH 配置已原子写入", failed.stdout)
        self.assertTrue(self.ssh_config.is_dir(), "directory target was replaced")
        self.assertEqual(stat.S_IMODE(self.ssh_config.stat().st_mode), 0o755, "directory target was chmod'ed")
        self.assertEqual(stat.S_IMODE(self.ssh_config.parent.stat().st_mode), ssh_dir_mode)
        self.assertEqual(
            sorted(path.name for path in self.ssh_config.parent.glob(f"{self.ssh_config.name}.backup.*")),
            backups_before, "directory target produced a backup",
        )

    def test_ssh_option_creates_a_missing_config_with_mode_600(self) -> None:
        self.ssh_config.unlink()
        result = self.run_menu("2\n", "0\n")
        self.assertIn("pass SSH 配置已原子写入", result.stdout)
        self.assertTrue(self.ssh_config.is_file())
        self.assertEqual(stat.S_IMODE(self.ssh_config.stat().st_mode), 0o600)
        written = self.ssh_config.read_text()
        self.assertTrue(written.startswith("# >>> tun-fix.sh github ssh >>>\n"))
        self.assertIn("Host github.com ssh.github.com", written)
        self.assertNotIn("ProxyCommand", written)
        self.assertNotIn("ProxyJump", written)
        self.assertEqual(list(self.ssh_config.parent.glob(f"{self.ssh_config.name}.backup.*")), [])
        self.assertEqual(sorted(path.name for path in self.ssh_config.parent.iterdir()
                                if ".config." in path.name and path.name != self.ssh_config.name), [])

    def test_ssh_write_cap_never_commits_a_truncated_config(self) -> None:
        """A short render (ENOSPC/quota class) must not replace unrelated entries."""
        original = self.unowned_ssh_config(hosts=60)
        before = self.ssh_config.read_bytes()
        environment = self.ssh_failure_environment()
        # The 2046-byte original fits the 2048-byte cap while the ~2.5 KB render
        # does not, so the render is guaranteed to be cut short.
        result = subprocess.run(
            ["bash", "-c", 'trap "" XFSZ; ulimit -f 2; exec bash "$0"', str(ENTRY)],
            cwd=str(self.root), env=environment, input="2\n0\n",
            text=True, capture_output=True, check=False, timeout=120,
        )
        self.assertNotEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertNotIn("pass SSH 配置已原子写入", result.stdout)
        self.assertIn("fail ", result.stdout + result.stderr)
        self.assert_ssh_write_failed_closed(before, backups=0)
        self.assertEqual(self.ssh_config.read_text(), original)
        self.assertIn("Host host59.example", self.ssh_config.read_text())

    def test_ssh_render_guards_a_failing_or_empty_block_producer(self) -> None:
        original = self.unowned_ssh_config()
        before = self.ssh_config.read_bytes()
        environment = self.ssh_failure_environment()
        for label, producer in (
            ("return-3", 'github_ssh_block() { printf "partial" >&2; return 3; }'),
            ("empty", "github_ssh_block() { :; }"),
        ):
            result = subprocess.run(
                ["bash", "-c", f'source "$1"; {producer}; configure_ssh', "test", str(ENTRY)],
                cwd=str(self.root), env=environment, text=True, capture_output=True, check=False, timeout=120,
            )
            self.assertEqual(result.returncode, 1, f"{label}: {result.stdout}{result.stderr}")
            self.assertNotIn("pass SSH 配置已原子写入", result.stdout)
            self.assertEqual(self.ssh_config.read_bytes(), before, label)
            self.assertEqual(stat.S_IMODE(self.ssh_config.stat().st_mode), 0o644, label)
            self.assertEqual(sorted(path.name for path in self.ssh_config.parent.iterdir()
                                    if ".config." in path.name and path.name != self.ssh_config.name), [], label)
        self.assertEqual(self.ssh_config.read_text(), original)

    # ---- SSH isolation --------------------------------------------------
    def test_option_two_only_touches_ssh_config_and_its_backup(self) -> None:
        self.declare_wechat_proxy()
        before = self.snapshot(include_mtime=True)
        result = self.run_menu("2\n", "0\n")
        after = self.snapshot(include_mtime=True)
        changed = self.changed_paths(before, after)
        ssh_backups = sorted(self.ssh_config.parent.glob(f"{self.ssh_config.name}.backup.*"))
        allowed = {str(self.ssh_config)} | {str(path) for path in ssh_backups}
        self.assertTrue(changed <= allowed, f"SSH option touched unexpected paths: {sorted(changed - allowed)}")
        self.assertIn(str(self.ssh_config), changed)
        self.assertEqual(len(ssh_backups), 1)
        require(BACKUP_RE.search(ssh_backups[0].name), ssh_backups[0].name)
        self.assertIn("Host existing.example", self.ssh_config.read_text())
        self.assertIn("Host github.com ssh.github.com", self.ssh_config.read_text())
        self.assertIn("IPQoS none", self.ssh_config.read_text())
        self.assertNotIn("ProxyCommand", self.ssh_config.read_text())
        self.assertNotIn("ProxyJump", self.ssh_config.read_text())
        self.assertIn("ssh.github.com", result.stdout)
        self.assertIn("pass SSH", result.stdout)
        self.assertEqual(stat.S_IMODE(self.ssh_config.stat().st_mode), 0o600)
        self.assertEqual(sorted(path.name for path in self.ssh_config.parent.iterdir()
                                if ".config." in path.name and path.name != self.ssh_config.name), [])
        self.assertEqual(self.script.read_text(), "// Generated by tun-fix.sh earlier revision\n")
        self.assertEqual(self.backups(), [])

    def test_option_two_reports_static_check_failure_and_still_writes_config(self) -> None:
        (self.bin / "ssh").write_text(
            "#!/bin/bash\n"
            "printf '%s\\n' \"$*\" >> \"${SSH_LOG:?}\"\n"
            "printf 'host github.com\\nhostname github.com\\nport 22\\nipqos lowdelay throughput\\n'\n",
            encoding="utf-8",
        )
        (self.bin / "ssh").chmod(0o755)
        result = self.run_menu("2\n", "0\n", expected=1)
        self.assertIn("fail SSH", result.stdout)
        self.assertIn("Host github.com ssh.github.com", self.ssh_config.read_text())
        self.assertTrue(self.ssh_log.exists())

    def test_ssh_option_preserves_unowned_blocks_and_declines_eof(self) -> None:
        # An unowned github.com Host entry exercises both the hint and the prompt.
        self.ssh_config.write_text(
            "# existing host\nHost existing.example github.com\n    Port 22\n"
            "Host other.example\n    Port 2200\n",
            encoding="utf-8",
        )
        original = self.ssh_config.read_text()
        declined = self.run_menu("2\n", "n\n", "0\n")
        self.assertIn("已取消 SSH 配置", declined.stdout)
        self.assertEqual(self.ssh_config.read_text(), original)
        self.assertEqual(list(self.ssh_config.parent.glob(f"{self.ssh_config.name}.backup.*")), [])

        confirmed = self.run_menu("2\n", "y\n", "0\n")
        self.assertIn("Host github.com ssh.github.com", self.ssh_config.read_text())
        self.assertIn("Host other.example", self.ssh_config.read_text())
        self.assertEqual(len(list(self.ssh_config.parent.glob(f"{self.ssh_config.name}.backup.*"))), 1)

    # ---- generated artifact guards --------------------------------------
    def test_generated_script_preserves_guard_and_exact_policy_identity(self) -> None:
        node = shutil.which("node")
        if node is None:
            self.skipTest("node is required for the Script host guard fixture")
        core = shutil.which("verge-mihomo")
        if core is None:
            self.skipTest("verge-mihomo is required for the core validation fixture")
        self.declare_wechat_proxy()
        self.run_menu("\n", "0\n")
        source = self.script.read_text()

        base = {
            "proxies": [],
            "proxy-groups": [{"name": "Proxy", "type": "select", "proxies": ["DIRECT"]}],
            "rules": ["DOMAIN-SUFFIX,example,DIRECT", "DOMAIN,force.example,DIRECT", "MATCH,Proxy"],
        }
        ordered = self.host_wrapped_js(node, source, base)["rules"]
        self.assertEqual(ordered, [
            "DOMAIN,force.example,DIRECT",
            f"PROCESS-PATH,{self.app_executable},Proxy",
            "DOMAIN-SUFFIX,example,DIRECT",
            "DOMAIN-SUFFIX,cn,DIRECT",
            "MATCH,Proxy",
        ])
        self.core_validate(core, {**base, "rules": ordered}, "valid", 0)

        missing_group = self.host_wrapped_js(node, source, {"proxies": [], "proxy-groups": [], "rules": ["MATCH,DIRECT"]})
        output = self.core_validate(core, missing_group, "missing-group", 1)
        self.assertIn("LOCAL-RULES-ERROR-MISSING-PROXY-GROUP", output)
        missing_match = self.host_wrapped_js(node, source, {
            "proxies": [],
            "proxy-groups": [{"name": "Proxy", "type": "select", "proxies": ["DIRECT"]}],
            "rules": [],
        })
        output = self.core_validate(core, missing_match, "missing-match", 1)
        self.assertIn("LOCAL-RULES-ERROR-MISSING-MATCH", output)

    def host_wrapped_js(self, node: str, script: str, config: dict) -> dict:
        """Model Verge 2.5.2's JSON return path: a throw would return the original config."""
        program = r'''
const fs = require('fs'), vm = require('vm');
const sandbox = {}; vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(process.argv[1], 'utf8'), sandbox);
const original = JSON.parse(process.argv[2]);
let returned;
try {
  const serialized = JSON.stringify(sandbox.main(original) || '');
  const parsed = JSON.parse(serialized);
  if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') throw new Error('mapping required');
  returned = parsed;
} catch (_) {
  returned = original;
}
console.log(JSON.stringify(returned));
'''
        script_path = self.root / "host-guard.js"
        script_path.write_text(script, encoding="utf-8")
        result = subprocess.run([node, "-e", program, str(script_path), json.dumps(config)],
                                text=True, capture_output=True, check=False, timeout=60)
        self.assertEqual(result.returncode, 0, result.stderr)
        return json.loads(result.stdout)

    def core_validate(self, core: str, config: dict, name: str, expected: int) -> str:
        config_file = self.root / f"{name}.yaml"
        subprocess.run(
            ["python3", "-c", "import json,sys,yaml; yaml.safe_dump(json.load(sys.stdin), sys.stdout)"],
            input=json.dumps(config), text=True, stdout=config_file.open("w"), check=True,
        )
        result = subprocess.run([core, "-t", "-f", str(config_file)], text=True,
                                capture_output=True, check=False, timeout=60)
        self.assertEqual(result.returncode, expected,
                         f"core {name} rc={result.returncode}, expected {expected}:\n{result.stdout}\n{result.stderr}")
        return result.stdout + result.stderr

    # ---- retained CLI entrypoints ---------------------------------------
    def test_rules_check_and_render_stay_read_only_and_registry_free(self) -> None:
        no_registry = dict(self.environment())
        (self.state / "profiles.yaml").unlink()
        checked = self.run_entry("rules", "check", environment=no_registry)
        self.assertIn("route sources valid", checked.stdout)
        rendered = self.run_entry("rules", "render", environment=no_registry)
        self.assertTrue(rendered.stdout.startswith("// Generated by tun-fix.sh"))
        self.assertFalse((self.state / "profiles.yaml").exists())
        self.assertEqual(self.script.read_text(), "// Generated by tun-fix.sh earlier revision\n")

    def test_removed_commands_are_not_reachable(self) -> None:
        for arguments in (("optimize",), ("backup",), ("repair",), ("rules", "backup")):
            result = subprocess.run(["bash", str(ENTRY), *arguments], cwd=str(self.root),
                                    env=self.environment(), text=True, capture_output=True, check=False, timeout=60)
            self.assertNotEqual(result.returncode, 0, arguments)
            self.assertIn("用法", result.stdout + result.stderr)

    def test_sourcing_the_entry_only_defines_functions(self) -> None:
        before = self.snapshot(include_mtime=True)
        result = subprocess.run(
            ["bash", "-c", f'source "{ENTRY}"; declare -f main; declare -f show_menu; declare -f restore_last_script'],
            env=self.environment(), cwd=str(self.root), text=True, capture_output=True, check=False, timeout=60,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("main ()", result.stdout)
        self.assertIn("show_menu ()", result.stdout)
        self.assertIn("restore_last_script ()", result.stdout)
        self.assertEqual(self.changed_paths(before, self.snapshot(include_mtime=True)), set())


if __name__ == "__main__":
    unittest.main(verbosity=2)
