import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFileSync, spawn } from "node:child_process";
import { readFileSync, readdirSync, watch, type FSWatcher } from "node:fs";
import * as os from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { aggregateLogicalState, HEARTBEAT_MS, publishLease, seedAttentionWatermarksFromSnapshot } from "./state.mjs";
const STARTED = "subagent:async-started", COMPLETE = "subagent:async-complete", CONTROL = "subagent:control-event";
const HERE = dirname(fileURLToPath(import.meta.url)), ANIMATOR = join(HERE, "animator.mjs");
type Identity = { socketPath: string; windowId: string; paneId: string };
type NestedRoute = { rootRunId: string; eventSink: string; controlInbox: string; capabilityToken: string; registryPath: string; registryDir: string };
type Child = { id: string; asyncDir?: string; nestedRoute?: NestedRoute; rootTerminal?: boolean; nestedProjection?: unknown };
type SessionManager = { getSessionFile?: () => string | null | undefined; getSessionId?: () => string | null | undefined };
const object = (x: unknown): Record<string, unknown> | undefined => x && typeof x === "object" ? x as Record<string, unknown> : undefined;
const NESTED_TERMINAL = new Set(["complete", "failed", "paused", "stopped", "rejected"]);
const HARD_EXCLUDE = /(abort|aborted|cancelled|context (length|overflow|window)|maximum context|max tokens|token limit|content policy|safety|refusal|refused)/i;
const POSITIVE_QUOTA = /(insufficient_user_quota|quota|quota exceeded|billing|balance(?!\s*transfer)|out of (balance|credit)|zero (balance|credit)|payment required|usage limit|quota will reset|weekly.{0,12}limit|purchase extra usage|upgrade your plan|(?:余额|额度|配额|套餐).{0,12}(?:不足|耗尽|用尽|为 0|为0))/i;
const POSITIVE_AUTH = /(api[-_ ]?key|authentication|unauthorized|forbidden|\b401\b|\b403\b)/i;
const POSITIVE_MODEL = /(invalid model|unknown model|model (id|name).*(invalid|unknown)|model not found|model does not exist|model.*(unavailable|not available))/i;
const POSITIVE_RATE = /(no deployments? available|deployment unavailable|\b429\b|rate[- ]limit|overloaded?|capacity|too many requests)/i;
const POSITIVE_TIMEOUT = /\b408\b|timeout|timed out/i;
const POSITIVE_TRANSPORT = /(^|\bError:\s*)terminated\s*$|network failure|fetch failed|connection (refused|reset|dropped)|econn(refused|reset)|socket hang up|streaming error|streaming failed|stream ended[- ]before|stream interrupted|transport error|transport.*failed/i;
const POSITIVE_5XX = /\b5\d\d\b|\b520\b|\b524\b|\b529\b/i;
const POSITIVE_ADAPTER = /LiteLLMCompletionStreamingIterator|completed_response/i;
const POSITIVE_CONCURRENCY = /(permission[_ ]?error.*concurrent|concurrent request limit)/i;
const POSITIVE_PROVIDER = /(service unavailable|provider (unavailable|error)|backend unavailable|upstream (unavailable|error))/i;
const POSITIVE_ANY = new RegExp([POSITIVE_QUOTA.source, POSITIVE_AUTH.source, POSITIVE_MODEL.source, POSITIVE_RATE.source, POSITIVE_TIMEOUT.source, POSITIVE_TRANSPORT.source, POSITIVE_5XX.source, POSITIVE_ADAPTER.source, POSITIVE_CONCURRENCY.source, POSITIVE_PROVIDER.source].join("|"), "i");
const ORDINARY_BAD_REQUEST = /(\b400\b|bad request|invalid request|schema|validation(?! failed))/i;
const CONFLICT_RATELIMIT = /too many concurrent requests/i;

export function classifyModelUnavailable(message: unknown) {
  const msg = object(message);
  const error = typeof msg?.errorMessage === "string" ? msg.errorMessage.trim() : "";
  if (msg?.role !== "assistant" || msg?.stopReason !== "error" || !error) return false;
  if (HARD_EXCLUDE.test(error)) return false;
  if (CONFLICT_RATELIMIT.test(error)) return true;
  if (ORDINARY_BAD_REQUEST.test(error)) {
    if (POSITIVE_MODEL.test(error)) return true;
    if (POSITIVE_QUOTA.test(error)) return true;
    if (POSITIVE_AUTH.test(error)) return true;
    return false;
  }
  return POSITIVE_ANY.test(error);
}
function partHasSemanticOutput(part: Record<string, unknown> | undefined) { if (!part) return false; if (typeof part.text === "string" && part.text.trim()) return true; if (typeof part.thinking === "string" && (part.thinking as string).trim()) return true; const t = String(part.type || ""); return t === "toolCall" || t === "tool_call" || t === "tool_use"; }
function assistantHasSemanticOutput(msg: Record<string, unknown> | undefined) { if (!msg || msg.role !== "assistant") return false; if (typeof msg.text === "string" && msg.text.trim()) return true; if (typeof msg.thinking === "string" && msg.thinking.trim()) return true; const content = Array.isArray(msg.content) ? msg.content : []; const delta = object(msg.delta); if (Array.isArray(delta?.content) && delta!.content.some((part) => partHasSemanticOutput(object(part)))) return true; return content.some((part) => partHasSemanticOutput(object(part))); }
function semanticAssistantOutput(message: unknown) { const p = object(message); if (!p) return false; if (assistantHasSemanticOutput(p)) return true; const inner = object(p.message); if (inner) return assistantHasSemanticOutput(inner); return false; }
export function nextModelErrorState(current: boolean, eventType: string, message?: unknown) { if (eventType === "model_select") return false; if (eventType === "message_update") { if (classifyModelUnavailable(message)) return true; return current && semanticAssistantOutput(message) ? false : current; } if (eventType === "message_end") { const msg = object(message); if (classifyModelUnavailable(message)) return true; if (msg?.role === "assistant" && msg?.stopReason !== "error" && msg?.stopReason !== "aborted") return false; return current; } return current; }
function eventMessage(args: unknown[]) { for (const arg of args) { const p = object(arg); if (object(p?.message)) return p?.message; if (p?.role === "assistant" || p?.role === "tool") return p; } return undefined; }
function unwrapAssistantMessage(value: unknown) { const p = object(value); if (object(p?.message)) return p?.message; if (p?.role === "assistant") return p; return undefined; }
function identity(): Identity { const pane = process.env.TMUX_PANE; if (!pane) throw new Error("pi-tmux-window-status: TMUX_PANE is missing; Pi is outside tmux"); const socketPath = execFileSync("tmux", ["display-message", "-p", "#{socket_path}"], { encoding: "utf8" }).trim(); const [windowId, paneId] = execFileSync("tmux", ["-S", socketPath, "display-message", "-p", "-t", pane, "#{window_id}|#{pane_id}"], { encoding: "utf8" }).trim().split("|"); if (!socketPath || !windowId || !paneId) throw new Error("pi-tmux-window-status: cannot resolve tmux socket/window/pane"); return { socketPath, windowId, paneId }; }
function readStatus(dir?: string) { if (!dir) return undefined; try { return JSON.parse(readFileSync(join(dir, "status.json"), "utf8")); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") console.error(`pi-tmux-window-status: malformed status: ${dir}/status.json`); return undefined; } }
function terminal(s: unknown) { return ["complete", "completed", "failed", "paused", "stopped", "rejected"].includes(String(s)); }
function statusRoot(status: unknown) { const p = object(status); return typeof p?.runId === "string" ? p.runId : typeof p?.id === "string" ? p.id : undefined; }
function statusTerminal(status: unknown) { return terminal(object(status)?.state); }
function stateOf(node: unknown) { const p = object(node); return typeof p?.state === "string" ? p.state : typeof p?.status === "string" ? p.status : undefined; }
function idOf(node: unknown, fallback?: string) { const p = object(node); return typeof p?.id === "string" ? p.id : typeof p?.runId === "string" ? p.runId : fallback; }
function isNestedLiveState(state: unknown) { return typeof state === "string" && !NESTED_TERMINAL.has(state); }
export function nestedPublisherDisabled(env = process.env) { return Number(env.PI_SUBAGENT_DEPTH || 0) > 0; }
export function childStillRunning(child: { exitCode: number | null; signalCode: string | null } | null | undefined) { return Boolean(child) && child!.exitCode === null && child!.signalCode === null; }
export function animatorSpawnNeeded(child: { exitCode: number | null; signalCode: string | null } | null | undefined, desired: boolean, force = false) { return Boolean(force || desired) && !childStillRunning(child); }
/** Mirrors pi-subagents 0.56 resolveTempScopeId: configured root, then uid, then user/home fallback. */
export function defaultAsyncRoot(env = process.env, uid = process.getuid?.(), tmp = os.tmpdir()) { const configured = env.PI_SUBAGENTS_TEMP_ROOT?.trim(); if (configured) return join(configured, "async-subagent-runs"); const scope = typeof uid === "number" ? `uid-${uid}` : env.USERNAME || env.USER || env.LOGNAME ? `user-${env.USERNAME || env.USER || env.LOGNAME}` : `home-${String(env.USERPROFILE || env.HOME || os.homedir()).trim().replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "") || "unknown"}`; return join(tmp, `pi-subagents-${scope}`, "async-subagent-runs"); }
export function restoredChildren(root: string, sessionId: string) { const found: Child[] = []; const active = join(root, ".active-runs"); try { for (const id of readdirSync(active)) { const dir = join(root, id); const status = readStatus(dir); const rootId = statusRoot(status) || id; if (status && !statusTerminal(status) && object(status)?.sessionId === sessionId) found.push({ id: rootId, asyncDir: dir, ...(validateNestedRoute(object(status)?.nestedRoute, rootId) ? { nestedRoute: validateNestedRoute(object(status)?.nestedRoute, rootId) } : {}) }); } } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") console.error("pi-tmux-window-status: cannot read pi-subagents active-run index", error); } return found; }
export function sessionIdOf(sessionManager: SessionManager | undefined) { const file = sessionManager?.getSessionFile?.(); if (typeof file === "string" && file) return file; const id = sessionManager?.getSessionId?.(); return typeof id === "string" && id ? id : undefined; }
export function validateNestedRoute(value: unknown, rootId: string): NestedRoute | undefined { const r = object(value); if (!r || r.rootRunId !== rootId) return undefined; const eventSink = typeof r.eventSink === "string" && r.eventSink ? r.eventSink : undefined, controlInbox = typeof r.controlInbox === "string" && r.controlInbox ? r.controlInbox : undefined, capabilityToken = typeof r.capabilityToken === "string" && r.capabilityToken ? r.capabilityToken : undefined; if (!eventSink || !controlInbox || !capabilityToken) return undefined; const registryDir = dirname(eventSink); return { rootRunId: rootId, eventSink, controlInbox, capabilityToken, registryDir, registryPath: join(registryDir, "registry.json") }; }
export function childFromStartedPayload(value: unknown, rootSessionId: string | undefined): Child | undefined { const p = object(value), id = typeof p?.id === "string" ? p.id : undefined, dir = typeof p?.asyncDir === "string" ? p.asyncDir : undefined, sessionId = typeof p?.sessionId === "string" ? p.sessionId : undefined; if (!id || !dir || !sessionId || !rootSessionId || sessionId !== rootSessionId) return undefined; return { id, asyncDir: dir, ...(validateNestedRoute(p?.nestedRoute, id) ? { nestedRoute: validateNestedRoute(p?.nestedRoute, id) } : {}) }; }
function nestedSourceChildren(node: unknown): unknown[] { const p = object(node); const children = Array.isArray(p?.children) ? p.children : []; const stepChildren = Array.isArray(p?.steps) ? p.steps.flatMap((step) => Array.isArray(object(step)?.children) ? object(step)!.children as unknown[] : []) : []; return [...children, ...stepChildren]; }
function nestedActivityFields(node: unknown) { const p = object(node), activity = object(p?.activity), out: Record<string, unknown> = {}; for (const key of ["activityState", "lastActivityAt", "currentToolStartedAt", "currentTool"] as const) if (p?.[key] !== undefined) out[key] = p[key]; if (activity) out.activity = Object.fromEntries(Object.entries(activity).filter(([key]) => ["state", "lastActivityAt", "currentToolStartedAt", "currentTool"].includes(key))); return out; }
function projectNestedNode(node: unknown, fallback: string): unknown[] { const id = idOf(node, fallback); const state = stateOf(node); if (!id || !state) return []; if (NESTED_TERMINAL.has(state)) return []; const children = nestedSourceChildren(node).flatMap((child, index) => projectNestedNode(child, `${id}:child:${index}`)); const projected = [{ id, state, ...nestedActivityFields(node) }]; if (children.length) projected[0]!.children = children; return projected; }
export function nestedProjectionFromChildren(rootRunId: string, children: unknown[]) { const projected = children.flatMap((child, index) => projectNestedNode(child, `${rootRunId}:child:${index}`)); return projected.length ? { runId: rootRunId, state: "complete", children: projected } : undefined; }

function hasLiveDescendant(node: unknown): boolean { if (!node || typeof node !== "object") return false; const state = stateOf(node); if (state && isNestedLiveState(state)) return true; return nestedSourceChildren(node).some((child) => hasLiveDescendant(child)); }
export function hasLiveNestedDescendant(node: unknown): boolean { return hasLiveDescendant(node); }
export function readNestedRegistryProjection(route: NestedRoute, read = readFileSync) { try { const registry = JSON.parse(String(read(route.registryPath, "utf8"))); if (!registry || registry.rootRunId !== route.rootRunId || !Array.isArray(registry.children)) return { resolved: false as const, live: true, reason: "mismatched" }; const live = registry.children.some((child: Record<string, unknown>) => hasLiveDescendant(child)); return { resolved: true as const, live, projection: nestedProjectionFromChildren(route.rootRunId, registry.children) || { runId: route.rootRunId, state: "complete" } }; } catch { return { resolved: false as const, live: true, reason: "unresolved" }; } }
export function mergedChildSnapshot(child: Child, rawStatus: unknown) { if (!child.rootTerminal) return rawStatus || child.nestedProjection; if (child.nestedProjection) return child.nestedProjection; if (child.nestedRoute) return undefined; return rawStatus; }
export function monitorNeeded(mainActive: boolean, childCount: number, modelError = false) { return Boolean(modelError || mainActive || childCount > 0); }

export default function piTmuxWindowStatus(pi: ExtensionAPI) {
  if (nestedPublisherDisabled()) return;
  let tmux: Identity; try { tmux = identity(); } catch (error) { console.error(error instanceof Error ? error.message : String(error)); return; }
  let mainActive = false, modelError = false, rootSessionId: string | undefined, beat: ReturnType<typeof setInterval> | undefined, animator: ReturnType<typeof spawn> | undefined, previousLeaseState: false | "active" | "error" = false;
  let lastAssistantErrorMatched = false, continueTimer: ReturnType<typeof setTimeout> | undefined, lastContinueSentAt = 0, autoContinueCount = 0;
  const AUTO_CONTINUE_MAX = 10, AUTO_CONTINUE_MIN_INTERVAL_MS = 30_000, AUTO_CONTINUE_DEBOUNCE_MS = 250;
  const owner = `${process.pid}:${tmux.paneId}`, children = new Map<string, Child>(), watchers = new Map<string, FSWatcher>(), routeWatchers = new Map<string, FSWatcher>(), attention = new Map<string, number>();
  const snapshots = () => new Map([...children].map(([id, c]) => { const snapshot = mergedChildSnapshot(c, readStatus(c.asyncDir)); seedAttentionWatermarksFromSnapshot(snapshot, attention); return [id, snapshot]; }));
  const logical = () => aggregateLogicalState({ mainActive, roots: new Set(children.keys()), snapshots: snapshots(), attentionWatermarks: attention });
  const diagnostic = () => { const state = logical(); return { parentSessionId: rootSessionId, activeRunIds: [...state.activeRoots].sort(), activeNodeIds: [...state.activeIds].sort() }; };
  const desiredLeaseState = () => modelError ? "error" : logical().active ? "active" : false;
  const kick = (force = false) => { if (!animatorSpawnNeeded(animator, Boolean(desiredLeaseState()), force)) return; animator = spawn(process.execPath, [ANIMATOR, tmux.socketPath], { detached: true, stdio: "ignore", env: process.env }); animator.unref(); };
  const closeChild = (id: string) => { const child = children.get(id); if (!child) return; for (const key of [...attention.keys()]) if (containsRun(child.nestedProjection, key) || containsRun(readStatus(child.asyncDir), key)) attention.delete(key); children.delete(id); watchers.get(id)?.close(); watchers.delete(id); routeWatchers.get(id)?.close(); routeWatchers.delete(id); };
  const watchNestedRoute = (id: string) => { const child = children.get(id); if (!child?.nestedRoute || routeWatchers.has(id)) return; try { const watcher = watch(child.nestedRoute.registryDir, (_event, name) => { if (!name || String(name) === "registry.json") { refreshNestedRegistry(id); sync(); } }); watcher.unref?.(); routeWatchers.set(id, watcher); } catch {} };
  const refreshNestedRegistry = (id: string) => { const child = children.get(id); if (!child?.nestedRoute) return; watchNestedRoute(id); const result = readNestedRegistryProjection(child.nestedRoute); if (!result.resolved) return; child.nestedProjection = result.projection; if (child.rootTerminal && !result.live) closeChild(id); };
  const refreshRetainedTerminalRoots = () => { for (const [id, child] of [...children]) if (child.rootTerminal && child.nestedRoute) refreshNestedRegistry(id); };
  const publishDesiredLease = () => { const next = desiredLeaseState(); publishLease(tmux, owner, next, Date.now(), process.env, diagnostic()); if (next) kick(); else if (previousLeaseState === "error") kick(true); previousLeaseState = next; return next; };
  const monitorTick = () => { refreshRetainedTerminalRoots(); publishDesiredLease(); if (!monitorNeeded(mainActive, children.size, modelError) && beat) { clearInterval(beat); beat = undefined; } };
  const sync = () => { publishDesiredLease(); if (monitorNeeded(mainActive, children.size, modelError)) { if (!beat) beat = setInterval(monitorTick, HEARTBEAT_MS); } else if (beat) { clearInterval(beat); beat = undefined; } };
  const refresh = (id: string) => { const child = children.get(id); if (!child) return; const status = readStatus(child.asyncDir); if (status && statusTerminal(status)) { child.rootTerminal = true; if (child.nestedRoute) refreshNestedRegistry(id); if (children.has(id) && !child.nestedRoute && !child.nestedProjection) closeChild(id); } else if (status) child.rootTerminal = false; sync(); };
  const watchChild = (id: string) => { const child = children.get(id); if (!child?.asyncDir || watchers.has(id)) return; try { const watcher = watch(child.asyncDir, (_event, name) => { if (!name || String(name) === "status.json") refresh(id); }); watcher.unref?.(); watchers.set(id, watcher); } catch (error) { console.error("pi-tmux-window-status: cannot watch async status", error); } };
  const started = (value: unknown) => { const p = object(value), id = typeof p?.id === "string" ? p.id : undefined, sessionId = typeof p?.sessionId === "string" ? p.sessionId : undefined; const child = childFromStartedPayload(value, rootSessionId); if (!child) { if (!id || typeof p?.asyncDir !== "string" || !sessionId) console.error("pi-tmux-window-status: malformed async-started payload (id, sessionId, and asyncDir required)"); else console.error(`pi-tmux-window-status: ignored foreign async-started '${id}'`); return; } children.set(child.id, { ...children.get(child.id), ...child }); watchChild(child.id); watchNestedRoute(child.id); sync(); };
  const complete = (value: unknown) => { const p = object(value), id = typeof p?.runId === "string" ? p.runId : typeof p?.id === "string" ? p.id : undefined, sessionId = typeof p?.sessionId === "string" ? p.sessionId : undefined; if (!id) { console.error("pi-tmux-window-status: malformed async-complete payload"); return; } if (sessionId && rootSessionId && sessionId !== rootSessionId) return; for (const [root, child] of [...children]) if (root === id || statusRoot(readStatus(child.asyncDir)) === id) { child.rootTerminal = true; if (Array.isArray(p?.nestedChildren)) { child.nestedProjection = nestedProjectionFromChildren(root, p.nestedChildren); if (child.nestedProjection && !child.nestedRoute) console.error(`pi-tmux-window-status: retaining terminal root '${root}' from completion nestedChildren without trusted nestedRoute; no authoritative sidecar can prove terminal, so it will remain failure-closed until session shutdown`); } if (child.nestedRoute) refreshNestedRegistry(root); if (children.has(root) && !child.nestedRoute && !child.nestedProjection) closeChild(root); } sync(); };
  function containsRun(node: unknown, id: string): boolean { const p = object(node); if (!p) return false; if (p.runId === id || p.id === id) return true; return (Array.isArray(p.steps) && p.steps.some((x) => containsRun(x, id))) || (Array.isArray(p.children) && p.children.some((x) => containsRun(x, id))); }
  const control = (value: unknown) => { const event = object(object(value)?.event); if (event?.type !== "needs_attention" || typeof event.runId !== "string") return; const nested = event.runId; let attributed = false; for (const child of children.values()) { const snapshot = mergedChildSnapshot(child, readStatus(child.asyncDir)); if (snapshot && containsRun(snapshot, nested)) { attention.set(nested, Date.now()); attributed = true; } } if (!attributed) console.error(`pi-tmux-window-status: needs_attention '${nested}' was not attributable to a known async status`); sync(); };
  const restore = () => { if (!rootSessionId) return; for (const child of restoredChildren(defaultAsyncRoot(), rootSessionId)) { children.set(child.id, child); watchChild(child.id); watchNestedRoute(child.id); } sync(); };
  const captureSession = (ctx: { sessionManager?: SessionManager }) => { rootSessionId ||= sessionIdOf(ctx.sessionManager); if (!rootSessionId) console.error("pi-tmux-window-status: root Pi session identity is unavailable"); };
  const updateModelError = (eventType: string, message?: unknown) => { const next = nextModelErrorState(modelError, eventType, message); if (next !== modelError) { modelError = next; sync(); } };
  const cancelContinue = () => { if (continueTimer) { clearTimeout(continueTimer); continueTimer = undefined; } };
  const sendContinue = () => { continueTimer = undefined; lastContinueSentAt = Date.now(); autoContinueCount += 1; pi.sendUserMessage("continue"); };
  const scheduleContinue = (delay: number) => { cancelContinue(); continueTimer = setTimeout(() => { if (mainActive) { continueTimer = undefined; return; } const idle = lastCtx?.isIdle?.() ?? false; const pending = lastCtx?.hasPendingMessages?.() ?? false; if (!idle || pending) { continueTimer = undefined; return; } const elapsed = Date.now() - lastContinueSentAt; if (elapsed < AUTO_CONTINUE_MIN_INTERVAL_MS) { scheduleContinue(AUTO_CONTINUE_MIN_INTERVAL_MS - elapsed); return; } if (autoContinueCount >= AUTO_CONTINUE_MAX) { continueTimer = undefined; return; } sendContinue(); }, delay); };
  const maybeAutoContinue = (ctx: { isIdle?: () => boolean; hasPendingMessages?: () => boolean }) => { lastCtx = ctx; if (!modelError || !lastAssistantErrorMatched || autoContinueCount >= AUTO_CONTINUE_MAX) return; if (!ctx.isIdle?.() || ctx.hasPendingMessages?.()) return; scheduleContinue(AUTO_CONTINUE_DEBOUNCE_MS); };
  let lastCtx: { isIdle?: () => boolean; hasPendingMessages?: () => boolean } | undefined;
  const resetFailureStreak = () => { autoContinueCount = 0; };
  const unsub = [pi.events.on(STARTED, started), pi.events.on(COMPLETE, complete), pi.events.on(CONTROL, control)];
  pi.on("session_start", (_event, ctx) => { captureSession(ctx); restore(); });
  pi.on("agent_start", (_event, ctx) => { captureSession(ctx); mainActive = true; cancelContinue(); restore(); sync(); });
  pi.on("agent_settled", (_event, ctx) => { mainActive = false; sync(); maybeAutoContinue(ctx); });
  pi.on("input", () => { cancelContinue(); });
  pi.on("message_update", (...args: unknown[]) => updateModelError("message_update", unwrapAssistantMessage(eventMessage(args)) || eventMessage(args)));
  pi.on("message_end", (...args: unknown[]) => { const msg = eventMessage(args); const matched = classifyModelUnavailable(msg); lastAssistantErrorMatched = matched; updateModelError("message_end", msg); if (!matched && object(msg)?.role === "assistant" && object(msg)?.stopReason !== "error" && object(msg)?.stopReason !== "aborted") resetFailureStreak(); });
  pi.on("model_select", () => { resetFailureStreak(); updateModelError("model_select"); });
  pi.on("session_shutdown", () => { const hadError = previousLeaseState === "error" || modelError; mainActive = false; modelError = false; lastAssistantErrorMatched = false; cancelContinue(); children.clear(); if (beat) clearInterval(beat); for (const watcher of watchers.values()) watcher.close(); watchers.clear(); for (const watcher of routeWatchers.values()) watcher.close(); routeWatchers.clear(); publishLease(tmux, owner, false); if (hadError) kick(true); for (const unsubscribe of unsub) if (typeof unsubscribe === "function") unsubscribe(); });
}
